### PR TITLE
Supply stdOut also to error handler

### PR DESCRIPTION
**Pull request by danez**
Currently when an error happens the error message only includes `stdErr`. In some cases (at least `push`) `stdOut` would be very handy to also have in the message because it contains the actual reason why something failed.
It appeared in renovatebot/renovate#8354 that we are not able to push because of permission problems, but the error handler in our code cannot handle the error because the reason is only printed to `stdOut` by git and therefore not in the error message.

To prove what is logged by `git` I add a `console.log` statement to  https://github.com/steveukx/git-js/blob/main/src/lib/runners/git-executor-chain.ts#L242-L248 and this is what I see.

```
stdErr ---> Pushing to https://edcd21d09ed4ed5d6d24e7b05369459ea2ccb17f@github.com/reactjs/react-tabs.git

stdErr ---> POST git-receive-pack (929 bytes)

stdErr ---> error: failed to push some refs to 'https://edcd21d09ed4ed5d6d24e7b05369459ea2ccb17f@github.com/reactjs/react-tabs.git'

stdOut ---> To https://github.com/reactjs/react-tabs.git
!       refs/heads/renovate/jamesives-github-pages-deploy-action-4.x:refs/heads/renovate/jamesives-github-pages-deploy-action-4.x       [remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/build.yml` without `workflow` scope)
Done
```

The fix simple concats `stdErr` and `stdOut`, so that the error message in the end has both.

Is this okay?

Ideally `stdOut` and `stdError` would be properties of the thrown Error (similar to [execa](https://github.com/sindresorhus/execa#handling-errors)), but that would be a way bigger undertaking.

### CODE REVIEW

**Comment by rarkins** [comment]
FYI I'm pretty sure we used to get these full messages passed up by `simple-git` and be able to detect them. i.e. Either `simple-git` changed its handling or GitHub changed how it its git returns errors.

**Comment by steveukx** [comment]
Hi, thank you for the pull request.

@rarkins the errors thrown by `simple-git` have always been just the content of `stdErr` is this related to running the `git push` with a different version of the `git` binary?

@danez I'll arrange for some tests and will have a new version out in the next couple of days for you that supports emitting errors with `stdOut` as well as `stdErr`.

**Comment by rarkins** [comment]
@steveukx good point! I forgot that possibility. We definitely would have changed git versions in this time too.

**Comment by steveukx** [comment]
Hi, you should now be able to update to version `2.37.0` which will include both the `stdOut` and `stdErr` content in the error message.

If you need to customise the detection of errors or the content included in the error message, you can now do so with the `errors` plugin: https://github.com/steveukx/git-js/blob/v2.37.0/docs/PLUGIN-ERRORS.md

**Pull request merged**
