### PR TITLE
Use close event instead of exit event as it also works on very fast

### PR DESCRIPTION
**Pull request by elwerene**
machines. See https://stackoverflow.com/questions/26446791/node-read-spawn-stderr-stdout-after-quick-exit-event

### CODE REVIEW

**Comment by steveukx** [comment]
Hi, thank you for highlighting this issue. I'll release a version now from #253 which will listen to both exit and close and use whichever comes first.

**Comment by elwerene** [comment]
@steveukx  You got my issue wrong. The issue isn't that one of those events comes first and the other later.
If you call the callback to early, there isn't yet any stdout to send so simple-git sends an empty callback even though the git command returns some data. My guess is, that the git command is too fast:

```
# time git branch -a -v > /dev/null
git branch -a -v > /dev/null  0,00s user 0,00s system 60% cpu 0,005 total
```

```
# git branch -a -v|wc -l
       5
```

If I run the ```branch``` command of simple-git in the same folder, I receive an empty response even though there are 5 branches in that git repository.

Thanks for your work!

**Comment by steveukx** [comment]
@elwerene ah, in that case - please can you run a check in your environment to confirm the order of the `data`, `close` and `exit` events from the underlying `child_process` object?

**Comment by elwerene** [comment]
@steveukx  I put some excessive logging into simple-git and ran it with my tool which runs hundreds of git command to checkout a whole development environment with about 20 git repositories. ```spawn``` is logged directly after creating the spawn. ```data```, ```
exit``` and ```close``` directly after getting called on these events.
Here's the log for one of these projects:

```
clone spawn
clone exit
checkout spawn
checkout exit
status spawn
status exit
branch spawn
status data
branch exit
checkout close
branch data
status close
branch close
```
at this point I cancelled the tool. It seems that a lot of the times the data comes after the exit event!

**Comment by steveukx** [comment]
That the `data` events come after both the `close` and `exit` events seems very strange - are you able to share the code for your tool with me at all? Are all of these calls being made through the same instance of `simple-git` or do they each use their own?

**Comment by elwerene** [comment]
I use one simple-git instance per repository. I can share the code with you, but probably not today as I need to set a license, remove some internal code and make it open source.. Probably tomorrow!

**Comment by Mortymus** [comment]
I stumbled upon the same issue:
When I run multiple simple-git instances in parallel to retrieve information (e.g. tags) from different repositories in parallel then simple git sometimes incorrectly returns empty result sets.

After some debugging I also found out that the child process events are triggered in this order when the error occurs:

1. exit
3. data on stdout
4. close

So data still comes in after exit but never after close.
This of course leads to the empty result as simple-git resolves after the exit event is triggered.

**Comment by elwerene** [comment]
uups, forgot about sending you the code O.o

**Comment by djmitche** [comment]
This is particularly easy to see with `await git('/').listRemote(['https://github.com/steveukx/git-js', 'master']);`.  In many cases, this returns an empty string for me.  I can only replicate this inside a fairly "busy" node process, though -- likely one in which the event loop calls callbacks in a nondeterministic order because there are lots of "ready" file descriptors.

**Comment by mlityn** [comment]
"Note that when the 'exit' event is triggered, child process stdio streams might still be open."
https://nodejs.org/api/child_process.html#child_process_event_exit

The 'close' event is emitted when the stdio streams of a child process have been closed. This is distinct from the 'exit' event, since multiple processes might share the same stdio streams.
https://nodejs.org/api/child_process.html#child_process_event_close

**Pull request closed without merging**
