### PR TITLE
show conflicted files

### PR DESCRIPTION
**Pull request by darrrk**

### CODE REVIEW

**Comment by steveukx** [comment]
Thanks, looks good. Before it can be merged, please can you add this to the tests.

**Comment by darrrk** [comment]
Sorry, absolutelly no have time. Maybe you can fastly write test after merge. Or maybe I can to understand how do it and write test too, but this happen no near time.

**Comment by steveukx** [comment]
To add this to the test for status, please modify the status tests (which are found around https://github.com/steveukx/git-js/blob/master/test/testCommands.js#L446).

To run the tests, you can use `npm test`

**Comment by darrrk** [comment]
Seems like that?

**Pull request merged**
