### PR TITLE
Allow status to take a directory argument

### LINKED ISSUE #467: status discards argument
`git status` accepts as an argument the directory to report on the status of. I am not able to pass this argument using simple-git.

### PR DESCRIPTION
**Pull request by conartist6**
Fixes #467

### CODE REVIEW

**Comment by conartist6** [comment]
I couldn't find existing test coverage of this so I tested the positive (path specified) and negative (path not specified) cases against my real world use case.

**Comment by conartist6** [comment]
reset will also need an directory argument.

**Comment by conartist6** [comment]
Actually it would also serve my use case if these commands just used the working directory (as set by the `cwd` command). @steveukx would you prefer that?

**Comment by conartist6** [comment]
And `checkout`

**Comment by steveukx** [comment]
Hi @conartist6, thank you for making the pull request.

Specifying the path(s) to act on is achieved in much the same way as any other variable argument, so it would keep the library more flexible if it was done by adding support for trailing options rather than having a specific argument.

`reset` and `checkout` had support for array options, but from version `2.10.0` they will support both array and object style. `status` wasn't using either, but now supports both.

I've added some [status integration tests cases](https://github.com/steveukx/git-js/blob/v2.10.0/test/integration/status.spec.js#L18-L36) that show how to use trailing pathspec options, and there is now [an example in the readme](https://github.com/steveukx/git-js/#using-a-pathspec-to-limit-the-scope-of-the-task)

**Comment by conartist6** [comment]
Ah great, thank you! The README example is super helpful.

**Pull request closed without merging**
