### PR TITLE
[fix] Fixing typing errors

### PR DESCRIPTION
**Pull request by OiYouYeahYou**
For some reason, my editor did not pick up these glaring error when I first finished

### CODE REVIEW

**Comment by vladbarosan** [comment]
@steveukx  can you please have a look and merge  ? right now consuming 1.95 in typescript fails on compile. Opened the issue https://github.com/steveukx/git-js/issues/275

**Comment by OiYouYeahYou** [comment]
Do you mean hold off of typescript definitions? Sure, but this needs to go through as peoples builds may fail because of this, it only needs to be a patch bump

**Comment by OiYouYeahYou** [comment]
Also, if you're working on a typescript branch offline, push it here so I could possibly do some work on it please?

**Comment by vladbarosan** [comment]
@steveukx right now I locked into 1.94 but I would say maybe release a 1.96 which reverts (or fixes ) the current issues so people are not broken if they use semvar

**Pull request merged**
